version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "80:5000"
        volumes:
            - ./server:/app
        environment:
            FLASK_ENV: "development"
            PYTHONUNBUFFERED: 1
